name: Get Changed Files as String

on:
  push:
    branches:
      - main  # 根据需要修改分支名称

jobs:
  list-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files as string
        id: changed_files_string
        run: |
          # 初始化一个空字符串来保存文件名
          changed_files_string=""
          
          # 遍历修改的文件，并将它们添加到字符串中
          # 使用 IFS 来确保文件名之间的分隔符是空格
          IFS=$'\n' read -d '' -r -a changed_files < <(git diff --name-only --diff-filter=ACMRTUXB origin/main...HEAD)
          for file in "${changed_files[@]}"; do
            # 使用 += 来追加字符串，并确保文件名之间有空格
            if [ -z "$changed_files_string" ]; then
              changed_files_string="$file"
            else
              changed_files_string="$changed_files_string $file"
            fi
          done
          
          # 输出结果作为环境变量（注意：这里假设文件名中不包含特殊字符，如换行符或引号）
          echo "::set-output name=files_string::$changed_files_string"

      - name: Print changed files string
        run: |
          # 从环境变量中读取拼接后的字符串并打印
          echo "Changed files (as string):"
          echo "${{ steps.changed_files_string.outputs.files_string }}"
