name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changed_files
        run: |
          files=$(git diff-tree --no-commit-id --name-only -r HEAD)
          echo "::set-output name=files::$files"
      - name: Run a multi-line script to send DingTalk message
        env:
          GITHUB_EVENT_HEAD_COMMIT_AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
          GITHUB_EVENT_HEAD_COMMIT_TIMESTAMP: ${{ github.event.head_commit.timestamp }}
          GITHUB_EVENT_HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          CHANGE_FILES: ${{ steps.changed_files.outputs.files }}
        run: |
          MSG="提交人：$GITHUB_EVENT_HEAD_COMMIT_AUTHOR_NAME\n提交时间：$(date -d "$GITHUB_EVENT_HEAD_COMMIT_TIMESTAMP" '+%Y-%m-%d %H:%M:%S')\n提交信息：$GITHUB_EVENT_HEAD_COMMIT_MESSAGE\n更改文件：$CHANGE_FILES"
          echo $MSG
          curl 'https://oapi.dingtalk.com/robot/send?access_token=5ad7d229c0ec7a34b3ff0bb6e168e368cbffecf0646bce2d9477434c4b77979e' -H 'Content-Type: application/json' -d "{\"msgtype\": \"text\",\"text\": {\"content\":\"$MSG\"}}"
