name: Get Changed Files

on:
  push:
    branches:
      - main  # 你可以根据需要修改这个分支名称

jobs:
  list-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed_files
        run: |
          # 获取修改的文件列表，并存储为数组
          changed_files=$(git diff --name-only --diff-filter=ACMRTUXB origin/main...HEAD)
          
          # 将文件列表转换为 JSON 数组格式，并输出为环境变量
          echo "::set-output name=files::$(echo \"$changed_files\" | jq -R . | jq -sRr 'split("\n")[:-1] | map(. | select(. != ""))')"

      - name: Print changed files
        run: |
          # 从环境变量中读取文件列表并打印
          echo "Changed files:"
          echo "${{ steps.changed_files.outputs.files }}" | jq -r '.[]' | while read -r file; do
            echo "  $file"
          done
